name: Build everything on merge

on:
  push:
    branches:
      - "main"

jobs:
  test-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run library tests
        run: ./gradlew quickpki-core:clean quickpki-core:test

  publish-lib:
    runs-on: ubuntu-latest
    needs: [test-library]
    if: "contains(github.event.head_commit.message, '[PUBLISH]')"
    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish quick-pki
        run: ./gradlew quickpki-core:build quickpki-core:publish -x test
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.ORG_GRADLE_PROJECT_nexusUsername }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.ORG_GRADLE_PROJECT_nexusPassword }}
