name: PR Build checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  test-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run library tests
        run: ./gradlew quickpki-core:clean quickpki-core:test
